---
#./ansible-playbook_wrapper create_project.yml -K -e "NAME_PROJECT=myproject"
- hosts: rancher-masters
  gather_facts: no
  roles:
  - {role: create-rancher-project, tags: create-rancher-project}
- hosts: "{{ NAME_PROJECT }}"
  gather_facts: no
  roles:
  - add-host-to-environment

- hosts: rancher-masters
  gather_facts: no
  roles:
  - {role: install-stack, STACK_NAME: janitor, tags: install-stack}
  - {role: install-stack, STACK_NAME: elk, tags: install-stack}
  - {role: install-stack, STACK_NAME: prometheus, tags: install-stack}