- name: launch master
  docker_container:
    name: rancherServer
    image: "{{rancher_master_image}}"
    restart_policy: always
    state: started
    ports:
    - "8080:8080"
    - "9345:9345"
    #required if you have a mirror registry
    env:
      CATTLE_BOOTSTRAP_REQUIRED_IMAGE="{{rancher_agent_image}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: [
      "--db-host {{ mysql_host }}",
      "--db-port 3306",
      "--db-user {{ mysql_user }}",
      "--db-pass {{ mysql_password }}",
      "--db-name {{ mysql_database }}",
      "--advertise-address {{ ansible_default_ipv4.address }}"
    ]
  become: true

- name: Wait until server is up
  wait_for:
    port: "{{ RANCHER_MASTER_PORT }}"
    delay: 30
