.catalog:
  name: "ELK"
  version: "v1.0"
  description: "Provide a ELK stack"
  uuid: elk-1
  questions:
    - variable: "LOG_CODEC"
      label: "Log Codec"
      description: "Logstash codec to catch application logs (json, plain)."
      default: json
      required: true
      type: "string"
logstash-indexer:
  metadata:
    logstash:
      inputs: |
        redis {
          host => "redis"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }
      filters: |
        mutate {
          rename => { "docker.id" => "container_id" }
          rename => { "docker.name" => "container_name" }
          rename => { "docker.image" => "docker_image" }
          rename => { "docker.hostname" => "docker_hostname" }
        }
      outputs: |
        elasticsearch {
          hosts => ["elasticsearch:9200"]
        }
logstash-collector:
  metadata:
    logstash:
      inputs: |
        udp {
          port => 5000
          codec => "json"
        }
      outputs: |
        redis {
          host => "redis"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }
logspout:
  scale: 1
elasticsearch:
  scale: 1
nginx-proxy-conf:
  scale: 1
  metadata:
    nginx: &id001
      conf:
        servername: kibana
        upstream_port: 5601
      users:
        '0':
          username: admin
          password: '{PLAIN}p0n3y'
kibana4:
  scale: 1
  metadata:
    nginx: *id001
nginx-proxy:
  scale: 1
  metadata:
    nginx: *id001
