---
#first time ./ansible-playbook_wrapper configure_host.yml -u yourgenericaccount -Kk  -e "NAME_PROJECT=myproject"
#second time ./ansible-playbook_wrapper configure_host.yml -K  -e "NAME_PROJECT=myproject"

- hosts: "{{ NAME_PROJECT }}"
  gather_facts: false
  tasks:
  - name: Make sure python is installed
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become: true

- hosts: "{{ NAME_PROJECT }}"
  roles:
  - {role: "AdopteUnOps.install-kernel", tags: "kernel"}
  - {role: "AdopteUnOps.configure-rsyslog", tags: "rsyslog"}
  - {role: "AdopteUnOps.configure-hostname", tags: "configure-hostname"}
  - {role: "AdopteUnOps.configure-ssh", tags: "configure-ssh"}
  - {role: "AdopteUnOps.install-debugging-tools", tags: "install-tools"}
  - {role: "AdopteUnOps.docker", tags: "install-docker"}
  - {role: "AdopteUnOps.upgrade-packages", tags: "upgrade-packages"}
  - {role: "AdopteUnOps.configure-unix-accounts", tags: "ops"}
