elasticsearch:
  image: elasticsearch:2.3.3
  volumes_from:
    - elasticsearch-datavolume
  labels:
    io.rancher.scheduler.affinity:host_label: role=tools
    io.rancher.sidekicks: elasticsearch-datavolume
elasticsearch-datavolume:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /usr/share/elasticsearch/data
    - /usr/share/elasticsearch/config
  entrypoint: /bin/true
  image: elasticsearch:2.3.3
redis:
  restart: always
  tty: true
  image: redis:3.0.3
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: role=tools
logstash-indexer-config:
  restart: always
  image: rancher/logstash-config:v0.2.0
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: role=tools
logstash-indexer:
  restart: always
  tty: true
  volumes_from:
  - logstash-indexer-config
  command:
  - logstash
  - -f
  - /etc/logstash
  image: logstash:2.1.1-1
  links:
  - redis:redis
  - elasticsearch:elasticsearch
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-indexer-config
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: role=tools
logstash-collector-config:
  restart: always
  image: rancher/logstash-config:v0.2.0
  labels:
    io.rancher.container.hostname_override: container_name
logstash-collector:
  restart: always
  tty: true
  links:
  - redis:redis
  ports:
  - "5000:5000/udp"
  - "25826:25826/udp"
  volumes_from:
  - logstash-collector-config
  command:
  - logstash
  - -f
  - /etc/logstash
  image: logstash:2.1.1-1
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-collector-config
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: role=tools
logspout:
  environment:
    LOGSPOUT: ignore
    ROUTE_URIS: logstash://logstash:5000
  links:
  - logstash-collector:logstash
  labels:
    io.rancher.scheduler.global: "true"
    io.rancher.container.hostname_override: container_name
  tty: true
  image: rancher/logspout-logstash:v0.2.0
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  stdin_open: true
nginx-proxy-conf:
  links:
  - elasticsearch:elasticsearch
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: role=tools
  command:
  - -backend=rancher
  - --prefix=/2015-07-25
  image: rancher/nginx-conf:v0.2.0
kibana4:
  environment:
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
  - elasticsearch:elasticsearch
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: role=tools
  tty: true
  image: kibana:4.4.2
  stdin_open: true
  net: container:nginx-proxy
nginx-proxy:
  links:
  - elasticsearch:elasticsearch
  labels:
    io.rancher.sidekicks: nginx-proxy-conf,kibana4
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: role=tools
  image: rancher/nginx:v1.9.4-3
  volumes_from:
  - nginx-proxy-conf
curator:
  links:
  - elasticsearch:elasticsearch
  labels:
    io.rancher.scheduler.affinity:host_label: role=tools
  image: sxmichael/curator-docker
  tty: true
  stdin_open: true
  environment:
    ELASTICSEARCH_HOST: elasticsearch
    ELASTICSEARCH_PORT: 9200
    MAX_INDEX_AGE: 15
