dependencies:
  - { role: lvm, disknames: "{{docker_disks}}", lvm_partitions: "{{docker_partitions}}", vg_name: "vg_docker", lv_name: "lv_docker", mount_point: "/var/lib/docker", when: use_docker_lvm}
